import { Component, computed, inject, signal } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { ApiService, Ticket } from './core/api.service';
import { ChatWidget } from './chat-widget/chat-widget';
import { LiveSupport } from './live-support/live-support';
import { ChatbotPage } from './chatbot-page/chatbot-page';
import { portalDisplayName, portalForRole } from './core/session-context';

type OperationalKind = 'tickets' | 'chat-sessions' | 'live-sessions';

@Component({ selector: 'app-root', standalone: true, imports: [CommonModule, FormsModule, ChatWidget, LiveSupport, ChatbotPage], templateUrl: './app.html', styleUrls: ['./app.scss', './app-bulk-delete.scss'] })
export class App {
  readonly standaloneChatbot = window.location.pathname.replace(/\/+$/, '') === '/chatbot';
  majorLinkId: number | null = null;
  api = inject(ApiService); view = signal('overview'); tickets = signal<Ticket[]>([]); catalog = signal<any>({ categories: [], services: [], priorities: [], statuses: [], assignmentGroups: [] }); admin = signal<any>({ groups: [], memberships: [], users: [], categories: [], services: [], rules: [], priorityRules: [], articles: [], botStatus: null, deletionInventory: { tickets: [], chatSessions: [], liveSessions: [] } }); selected = signal<Ticket | null>(null); loading = signal(false); error = signal(''); notice = signal(''); createAttachment?: File;
  readonly portalTitle = portalDisplayName(this.api.portalContext);
  login = { userName: '', password: '' }; ticket = { type: 'Incident', title: '', description: '', category: 'CTS Hardware', subcategory: 'Scanner Jam', priority: null, service: 'CTS Scanner', impact: 'Single User', urgency: 'Medium' }; comment = ''; workNote = ''; resolution = { code: 'Solved (Permanently)', notes: '' }; article = { title: '', content: '', keywords: '', category: 'CTS Hardware', subcategory: 'Scanner Jam', isPublished: true }; rule: any = { name: '', order: 100, category: '', subcategory: '', service: '', priority: '', ticketType: '', keywords: '', assignmentGroupId: null, isActive: true }; priorityRule: any = { name: '', description: '', keywords: '', category: '', service: '', priority: 'Low', order: 100, isActive: true }; newItem: any = { kind: 'groups', name: '', categoryId: null };
  userEditor = { userName: '', displayName: '', email: '', role: 'User', password: '', isActive: true };
  operationalSelection = signal<Record<OperationalKind, number[]>>({ tickets: [], 'chat-sessions': [], 'live-sessions': [] });
  metrics = computed(() => ({ total: this.tickets().length, active: this.tickets().filter(x => !['Resolved', 'Closed'].includes(x.status)).length, major: this.tickets().filter(x => x.type === 'Major Incident').length, resolved: this.tickets().filter(x => x.status === 'Resolved').length }));
  signIn() { this.error.set(''); this.api.login(this.login.userName, this.login.password).subscribe({ next: session => { const portal = portalForRole(session.role); if (!portal) { this.error.set('This account has an unsupported role.'); return; } window.location.assign(`/${portal}`); }, error: e => this.error.set(e.error?.error || e.message || 'Invalid username or password.') }); }
  logout() { this.api.logout(); this.tickets.set([]); this.view.set('overview'); window.location.assign('/'); }
  openChatbot() { window.open(`/chatbot?portal=${this.api.portalContext}`, '_blank', 'noopener,noreferrer'); }
  load() { this.loading.set(true); this.api.get<any>('/catalog').subscribe(c => this.catalog.set(c)); this.api.get<any[]>('/knowledge').subscribe(articles => this.admin.update(x => ({ ...x, articles }))); this.api.get<Ticket[]>('/tickets').subscribe({ next: t => { this.tickets.set(t); this.loading.set(false); }, error: () => this.loading.set(false) }); if (this.api.session()?.role === 'Admin') this.loadAdmin(); }
  loadAdmin() { this.api.get<any>('/admin/configuration').subscribe(x => this.admin.update(a => ({...a, ...x}))); this.api.get<any[]>('/admin/users').subscribe(users => this.admin.update(a => ({...a, users}))); this.api.get<any>('/admin/bot-status').subscribe(botStatus => this.admin.update(a => ({...a, botStatus}))); this.api.get<any>('/admin/deletion-inventory').subscribe(deletionInventory => this.admin.update(a => ({...a, deletionInventory}))); }
  navigate(view: string) { this.view.set(view); this.selected.set(null); if (view === 'admin') this.loadAdmin(); }
  createTicket() { this.error.set(''); if (!this.ticket.title.trim() || !this.ticket.description.trim()) { this.error.set('Title and description are required.'); return; } this.loading.set(true); this.api.post<Ticket>('/tickets', this.ticket).subscribe({ next: t => { const complete = () => { this.notice.set(`${t.number} created with ${t.priority} priority and routed to ${this.groupName(t.assignmentGroupId)}.`); this.ticket.title = ''; this.ticket.description = ''; this.createAttachment = undefined; this.loading.set(false); this.navigate('tickets'); this.load(); }; if (this.createAttachment) this.api.upload(t.id, this.createAttachment).subscribe({ next: complete, error: () => { this.error.set('Ticket created, but the attachment upload failed.'); complete(); } }); else complete(); }, error: e => { this.error.set(e.error?.error || 'Ticket could not be created.'); this.loading.set(false); } }); }
  selectCreateAttachment(event: Event) { this.createAttachment = (event.target as HTMLInputElement).files?.[0]; }
  openTicket(id: number) { this.api.get<Ticket>(`/tickets/${id}`).subscribe(t => { this.selected.set(t); this.view.set('detail'); }); }
  addComment() { const t = this.selected(); if (!t || !this.comment.trim()) return; this.api.post(`/tickets/${t.id}/comments`, { body: this.comment }).subscribe(() => { this.comment = ''; this.openTicket(t.id); }); }
  addWorkNote() { const t = this.selected(); if (!t || !this.workNote.trim()) return; this.api.post(`/tickets/${t.id}/work-notes`, { body: this.workNote }).subscribe(() => { this.workNote = ''; this.openTicket(t.id); }); }
  acceptTicket() { const t = this.selected(); if (t) this.api.post(`/tickets/${t.id}/accept`, {}).subscribe({ next: () => { this.notice.set('Ticket assigned to you.'); this.openTicket(t.id); this.load(); }, error: e => this.error.set(e.error?.error || 'Ticket could not be accepted.') }); }
  updateTicket(body: any) { const t = this.selected(); if (t) this.api.patch(`/tickets/${t.id}`, body).subscribe({ next: () => { this.openTicket(t.id); this.load(); }, error: e => this.error.set(e.error?.error || 'Update failed.') }); }
  resolveTicket() { if (!this.resolution.notes.trim()) { this.error.set('Resolution notes are required.'); return; } this.updateTicket({ resolutionCode: this.resolution.code, resolutionNotes: this.resolution.notes }); this.resolution.notes = ''; }
  updateStatus(status: string) { const t = this.selected(); if (!t) return; this.api.patch(`/tickets/${t.id}`, { status }).subscribe(() => this.openTicket(t.id)); }
  upload(event: Event) { const t = this.selected(); const file = (event.target as HTMLInputElement).files?.[0]; if (t && file) this.api.upload(t.id, file).subscribe({ next: () => this.openTicket(t.id), error: e => this.error.set(e.error?.error || 'Upload failed.') }); }
  addItem() { if (!this.newItem.name.trim()) return; this.api.post(`/admin/${this.newItem.kind}`, { name: this.newItem.name, isActive: true, categoryId: this.newItem.categoryId }).subscribe(() => { this.newItem.name = ''; this.loadAdmin(); this.load(); }); }
  addArticle() { this.api.post('/admin/articles', this.article).subscribe(() => { this.article = { title: '', content: '', keywords: '', category: 'CTS Hardware', subcategory: 'Scanner Jam', isPublished: true }; this.loadAdmin(); }); }
  addRule() { this.rule.assignmentGroupId = Number(this.rule.assignmentGroupId); this.api.post('/admin/rules', this.rule).subscribe(() => { this.rule = { name: '', order: 100, category: '', service: '', priority: '', ticketType: '', keywords: '', assignmentGroupId: null, isActive: true }; this.loadAdmin(); }); }
  addPriorityRule() { this.api.post('/admin/priority-rules', this.priorityRule).subscribe({ next: () => { this.priorityRule = { name: '', description: '', keywords: '', category: '', service: '', priority: 'Low', order: 100, isActive: true }; this.loadAdmin(); }, error: e => this.error.set(e.error?.error || 'Priority rule could not be created.') }); }
  savePriorityRule(rule: any) { this.api.put(`/admin/priority-rules/${rule.id}`, rule).subscribe({ next: () => { this.notice.set('Priority rule saved.'); this.loadAdmin(); }, error: e => this.error.set(e.error?.error || 'Priority rule could not be saved.') }); }
  remove(kind: string, id: number) { if (!confirm('Delete this configuration item?')) return; this.api.delete(`/admin/${kind}/${id}`).subscribe(() => this.loadAdmin()); }
  deleteOperationalData(kind: OperationalKind, item: any) { const description = kind === 'tickets' ? `${item.number} and all comments, work notes, history, attachment metadata and unreferenced physical files` : kind === 'chat-sessions' ? `chatbot session ${item.publicId} and its ${item.messageCount} messages` : `live-support session ${item.publicId} and its ${item.messageCount} transcript messages`; if (!confirm(`Permanently delete ${description}? This cannot be undone.`)) return; this.api.delete(`/admin/${kind}/${item.id}`).subscribe({ next: () => { this.setOperationalSelection(kind, item.id, false); this.notice.set('Administrative deletion completed and audited.'); this.loadAdmin(); this.load(); }, error: e => this.error.set(e.error?.error || 'Deletion failed.') }); }
  operationalItems(kind: OperationalKind): any[] { return this.admin().deletionInventory?.[kind === 'chat-sessions' ? 'chatSessions' : kind === 'live-sessions' ? 'liveSessions' : 'tickets'] || []; }
  selectedCount(kind: OperationalKind) { return this.operationalSelection()[kind].length; }
  isOperationalSelected(kind: OperationalKind, id: number) { return this.operationalSelection()[kind].includes(id); }
  allOperationalSelected(kind: OperationalKind) { const items = this.operationalItems(kind); return items.length > 0 && items.every(x => this.isOperationalSelected(kind, x.id)); }
  setOperationalSelection(kind: OperationalKind, id: number, selected: boolean) { this.operationalSelection.update(current => ({ ...current, [kind]: selected ? [...new Set([...current[kind], id])] : current[kind].filter(x => x !== id) })); }
  toggleOperationalSelection(kind: OperationalKind, id: number, event: Event) { this.setOperationalSelection(kind, id, (event.target as HTMLInputElement).checked); }
  toggleAllOperational(kind: OperationalKind, event: Event) { const checked = (event.target as HTMLInputElement).checked; this.operationalSelection.update(current => ({ ...current, [kind]: checked ? this.operationalItems(kind).map(x => x.id) : [] })); }
  bulkDeleteOperational(kind: OperationalKind) { const ids = this.operationalSelection()[kind]; if (!ids.length || !confirm(`Are you sure you want to delete ${ids.length} selected records? This action cannot be undone.`)) return; this.error.set(''); this.api.post<any>(`/admin/${kind}/bulk-delete`, { ids }).subscribe({ next: result => { this.operationalSelection.update(current => ({ ...current, [kind]: [] })); const failed = result.failed?.length || 0; const warnings = result.warnings?.length || 0; this.notice.set(failed || warnings ? `Deleted ${result.deletedCount} of ${result.requested} selected records. ${failed} could not be deleted${warnings ? `; ${warnings} file cleanup warning(s)` : ''}.` : `${result.deletedCount} selected records deleted successfully and audited.`); this.loadAdmin(); this.load(); }, error: e => this.error.set(e.error?.error || 'Selected records could not be deleted.') }); }
  saveMembership(userName: string, groupId: number, checked: boolean) { const existing = this.admin().memberships.filter((x: any) => x.userName === userName).map((x: any) => x.assignmentGroupId); const ids = checked ? [...new Set([...existing, groupId])] : existing.filter((x: number) => x !== groupId); this.api.put(`/admin/memberships/${userName}`, { userName, assignmentGroupIds: ids }).subscribe(() => this.loadAdmin()); }
  saveUser(user?: any) { const payload = user ? { ...user, password: null } : this.userEditor; this.api.post('/admin/users', payload).subscribe({ next: () => { this.userEditor = { userName: '', displayName: '', email: '', role: 'User', password: '', isActive: true }; this.loadAdmin(); }, error: e => this.error.set(e.error?.error || 'User could not be saved.') }); }
  hasMembership(userName: string, groupId: number) { return this.admin().memberships.some((x: any) => x.userName === userName && x.assignmentGroupId === groupId); }
  subcategories() { return this.catalog().categories.find((x: any) => x.name === this.ticket.category)?.subcategories || []; }
  groupName(id?: number) { return this.catalog().assignmentGroups.find((x: any) => x.id === id)?.name || this.admin().groups.find((x: any) => x.id === id)?.name || 'Unassigned'; }
  teamsLink(email?: string) { return email ? `https://teams.microsoft.com/l/chat/0/0?users=${encodeURIComponent(email)}` : null; }
  greeting() { return new Date().getHours() < 12 ? 'morning' : 'afternoon'; }
  ngOnInit() { if (!this.standaloneChatbot && this.api.portalContext !== 'default' && !this.api.session()) { window.location.replace('/'); return; } if (!this.standaloneChatbot && this.api.session()) { if (this.api.portalContext === 'agent') this.view.set('live'); this.load(); } }
}
